FROM node:16-alpine

WORKDIR /frontend

COPY frontend/package*.json ./

RUN npm install

COPY frontend/ ./

ARG REACT_APP_API_BASE_URL
ENV REACT_APP_API_BASE_URL=$REACT_APP_API_BASE_URL

RUN npm run build

EXPOSE 3000

RUN npm install -g serve

CMD ["serve", "-s", "build", "-l", "3000"]