FROM node:16-alpine AS build

WORKDIR /frontend

COPY frontend/package*.json ./

RUN npm install

COPY frontend/ ./

ARG REACT_APP_API_BASE_URL
ARG REACT_APP_GA_MEASUREMENT_ID

RUN REACT_APP_API_BASE_URL=$REACT_APP_API_BASE_URL \
    REACT_APP_GA_MEASUREMENT_ID=$REACT_APP_GA_MEASUREMENT_ID \
    npm run build

FROM node:16-alpine

RUN npm install -g serve

WORKDIR /app

COPY --from=build /frontend/build ./build

EXPOSE 3000

CMD ["serve", "-s", "build", "-l", "3000"]