name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      - name: Build Docker images
        run: |
          docker compose build
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          FRONTEND_API_BASE_URL: ${{ secrets.FRONTEND_API_BASE_URL }}

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Deploy to DigitalOcean
        run: |
          scp -o StrictHostKeyChecking=no -r -i ~/.ssh/deploy_key ./* root@${{ secrets.DROPLET_IP }}:/root/rating-guessr
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key -v root@${{ secrets.DROPLET_IP }} << EOF
            cd /root/rating-guessr
            docker compose down --volumes
            docker compose up -d --build
          EOF
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Clean up
        run: |
          docker image prune -f
          docker volume prune -f