name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Add SSH private key to agent
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          DISPLAY: ":99"
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519_temp
          chmod 600 ~/.ssh/id_ed25519_temp
          eval "$(ssh-agent -s)"
          SSH_ASKPASS=echo DISPLAY=:99 ssh-add ~/.ssh/id_ed25519_temp

      - name: Build Docker images
        run: |
          docker compose build
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          FRONTEND_API_BASE_URL: ${{ secrets.FRONTEND_API_BASE_URL }}

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Deploy to DigitalOcean
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          scp -o StrictHostKeyChecking=no -r ./* root@${{ secrets.DROPLET_IP }}:/root/rating-guessr
          ssh -o StrictHostKeyChecking=no -v root@${{ secrets.DROPLET_IP }} << EOF
            cd /root/rating-guessr
            docker compose down --volumes
            docker compose up -d --build
          EOF

      - name: Clean up
        run: |
          docker image prune -f
          docker volume prune -f